name = "amzn"
compatibility_date = "2022-01-31"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.8"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
